spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musicstore
    username: klau90
    password: Hipph*pp90
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
